name: data-workflow

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '35 0 * * *'

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib pandas
          pip install packaging

      - name: Crear archivo de credenciales
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Ejecutar script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
        run: python intento_google_sheet.py

#          git config user.name 'github-actions'
